### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [ology/Game-Battleship#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by ology** [comment]
"No one can use [this] code" is a bit extreme and overly dramatic.

This code, on github, is the "pre-build stage."  The license is added once the distribution is created with Dist::Zilla.

The official distribution is at https://metacpan.org/pod/Game::Battleship and most definitely includes a proper license.

**Comment by ology** [comment]
I will work on adding a license file to all of my github repos.  Thank you for pointing out the problem. :-)

**Comment by ology** [comment]
Fixed.
